"""Export a composable AML pattern-program draft from the composition forest.

This script turns the mined motion-pattern forest into a program-facing
artifact. It does not promote nodes as final labels and does not add
case-specific rules.

Pipeline:
1. Read the composition forest generated by
   `build_hml3d_composition_pattern_forest_v0.py`.
2. Preserve the hierarchy:
   composition_root -> structure_group -> composition_family -> variant.
3. Build condition entries for structure groups and families.
4. Export a compact program JSON plus a readable tree.

Quick run:
    python scripts/export_aml_composable_pattern_program_v0.py

Smoke test:
    python scripts/export_aml_composable_pattern_program_v0.py --self-test
"""

from __future__ import annotations

import argparse
import json
import tempfile
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


DEFAULT_FOREST_JSON = Path(
    "outputs/aml_regression_testset_v2/hml3d_composition_pattern_forest_v0_structure_groups/composition_pattern_forest.json"
)
DEFAULT_OUTPUT_DIR = Path("outputs/aml_regression_testset_v2/aml_composable_pattern_program_v0")


ROOT_KIND_MAP = {
    "composition_full_candidates": "full_body_compositions",
    "transition_candidates": "transitions",
    "component_coordination_candidates": "components",
    "context_diagnostic_candidates": "diagnostics",
}


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=True, indent=2), encoding="utf-8")


def _safe_id(text: str) -> str:
    out: list[str] = []
    for ch in text.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in {"_", "-"}:
            out.append(ch)
        else:
            out.append("_")
    value = "".join(out).strip("_")
    while "__" in value:
        value = value.replace("__", "_")
    return value or "unnamed"


def _child_index(edges: list[dict[str, Any]]) -> dict[str, list[str]]:
    out: dict[str, list[str]] = defaultdict(list)
    for edge in edges:
        parent = str(edge.get("parent_node_id") or "")
        child = str(edge.get("child_node_id") or "")
        if parent and child:
            out[parent].append(child)
    return out


def _review_status(node: dict[str, Any]) -> str:
    parent_root = str(node.get("parent_root") or "")
    status = str(node.get("status") or "")
    if parent_root == "context_diagnostic_candidates" or "diagnostic" in status:
        return "diagnostic_only"
    if parent_root == "component_coordination_candidates" or "component" in status:
        return "component_candidate"
    if parent_root == "transition_candidates" or "transition" in status:
        return "transition_candidate"
    if status.startswith("name_aligned"):
        return "review_candidate"
    return "candidate"


def _condition_scope(node: dict[str, Any]) -> str:
    parent_root = str(node.get("parent_root") or "")
    if parent_root == "composition_full_candidates":
        return "full_composition_candidate"
    if parent_root == "transition_candidates":
        return "transition_candidate"
    if parent_root == "component_coordination_candidates":
        return "component_candidate"
    return "diagnostic_candidate"


def _condition_id(label: str) -> str:
    return "AMLCP_" + _safe_id(label).upper()


def _unique_sorted(values: list[Any] | tuple[Any, ...]) -> list[str]:
    return sorted({str(value) for value in values if str(value)})


def _axis_tokens(node: dict[str, Any]) -> dict[str, list[str]]:
    channels = _unique_sorted(list(node.get("channels") or []))
    zones = _unique_sorted(list(node.get("zones") or []))
    family_core = _unique_sorted(list(node.get("family_core_items") or []))
    geometry = _unique_sorted(list(node.get("geometry_clusters") or []) + list(node.get("items") or []))
    cluster_ids: list[str] = []
    family_ids: list[str] = []
    for item in geometry + family_core:
        text = str(item)
        if "/" in text:
            family_ids.append(text.split("/", 1)[0].split(":", 1)[-1])
            cluster_ids.append(text.rsplit("/", 1)[-1])
        elif ":" in text:
            family_ids.append(text.split(":", 1)[-1])
        else:
            family_ids.append(text)
    return {
        "channels": channels,
        "zones": zones,
        "geometry_roles": geometry,
        "family_core_items": family_core,
        "event_families": _unique_sorted(family_ids),
        "cluster_ids": _unique_sorted(cluster_ids),
    }


def _semantic_level(node: dict[str, Any]) -> str:
    source_kind = str(node.get("node_kind") or "")
    parent_root = str(node.get("parent_root") or "")
    axes = _axis_tokens(node)
    channel_count = len(axes["channels"])
    has_root = any(channel.startswith("root_") for channel in axes["channels"])
    has_vertical = "whole_body_vertical" in axes["channels"]
    has_upper = any(channel in {"left_arm", "right_arm", "bimanual", "torso"} for channel in axes["channels"])
    has_lower = any(channel in {"left_leg", "right_leg", "support_gait"} for channel in axes["channels"])
    if source_kind == "composition_root":
        return "taxonomy_root"
    if parent_root == "component_coordination_candidates":
        return "component"
    if parent_root == "transition_candidates":
        return "transition"
    if parent_root == "context_diagnostic_candidates":
        return "diagnostic_context"
    if channel_count >= 3 and (has_root or has_vertical) and (has_upper or has_lower):
        return "whole_body_pattern_candidate"
    if channel_count >= 2:
        return "multi_part_coordination"
    return "local_component"


def _composition_policy(node: dict[str, Any]) -> str:
    level = _semantic_level(node)
    if level == "whole_body_pattern_candidate":
        return "may_bind_as_full_pattern_after_review"
    if level == "multi_part_coordination":
        return "may_bind_as_composed_subpattern"
    if level == "transition":
        return "bind_as_temporal_transition_or_phase"
    if level == "component":
        return "bind_as_reusable_component"
    if level == "local_component":
        return "bind_as_local_edit_handle"
    if level == "diagnostic_context":
        return "diagnostic_only_do_not_train_positive"
    return "grouping_only"


def _edit_scope(node: dict[str, Any]) -> str:
    level = _semantic_level(node)
    axes = _axis_tokens(node)
    channels = set(axes["channels"])
    if level == "whole_body_pattern_candidate":
        return "whole_body"
    if level in {"multi_part_coordination", "transition"}:
        return "multi_part"
    if channels & {"left_arm", "right_arm", "bimanual"}:
        return "upper_body_or_arm"
    if channels & {"left_leg", "right_leg", "support_gait"}:
        return "lower_body_or_leg"
    if channels & {"root_locomotion", "root_rotation", "whole_body_vertical"}:
        return "root_or_body"
    return "local"


def _match_signature(node: dict[str, Any]) -> dict[str, Any]:
    axes = _axis_tokens(node)
    source_kind = str(node.get("node_kind") or "")
    min_channels = 0 if source_kind == "composition_root" else max(1, min(2, len(axes["channels"])))
    return {
        "match_version": "aml_composable_match_signature_v0",
        "required_channels": axes["channels"],
        "required_zones": axes["zones"],
        "required_cluster_ids": axes["cluster_ids"],
        "required_event_families": axes["event_families"],
        "geometry_roles": axes["geometry_roles"],
        "family_core_items": axes["family_core_items"],
        "min_channel_overlap": min_channels,
        "min_cluster_overlap": 0,
        "min_event_family_overlap": 1 if axes["event_families"] else 0,
        "temporal_relation": "coactivation_or_nested_span",
        "support_hint": {
            "support_cases_max": int(node.get("support_cases_max") or node.get("support_cases") or 0),
            "support_cases_sum": int(node.get("support_cases_sum") or node.get("support_cases") or 0),
            "structure_score_max": float(node.get("structure_score_max") or node.get("structure_score") or 0.0),
        },
    }


def _edit_handles(node: dict[str, Any]) -> list[dict[str, str]]:
    text = " ".join(
        [
            str(node.get("motion_structure_label") or ""),
            " ".join(str(item) for item in node.get("family_core_items") or []),
            " ".join(str(item) for item in node.get("channels") or []),
            " ".join(str(item) for item in node.get("zones") or []),
        ]
    ).lower()
    handles: list[dict[str, str]] = [
        {"name": "span", "type": "temporal", "description": "start/end frame interval"},
        {"name": "count", "type": "numeric", "description": "repetition or phase count when available"},
    ]
    if "vertical" in text:
        handles.append({"name": "vertical_amplitude", "type": "numeric", "description": "body height or vertical impulse amplitude"})
    if "low_body" in text or "torso_forward_low_body" in text:
        handles.append({"name": "body_level", "type": "numeric", "description": "low-body depth or rise/descent amount"})
    if "leg_forward" in text or "leg:" in text:
        handles.append({"name": "leg_extension", "type": "numeric", "description": "forward leg extension or impulse magnitude"})
        handles.append({"name": "leg_side", "type": "categorical", "description": "left/right/bilateral leg role when recoverable"})
    if "arm" in text or "bimanual" in text:
        handles.append({"name": "arm_height", "type": "numeric", "description": "hand or arm elevation"})
        handles.append({"name": "arm_symmetry", "type": "categorical", "description": "unilateral/bilateral arm role"})
    if "root_locomotion" in text:
        handles.append({"name": "root_direction", "type": "categorical", "description": "root translation direction"})
        handles.append({"name": "distance", "type": "numeric", "description": "root translation distance"})
    if "root_rotation" in text:
        handles.append({"name": "turn_angle", "type": "numeric", "description": "root yaw angle"})
        handles.append({"name": "turn_direction", "type": "categorical", "description": "left/right turn direction"})

    seen: set[str] = set()
    unique: list[dict[str, str]] = []
    for handle in handles:
        name = handle["name"]
        if name in seen:
            continue
        seen.add(name)
        unique.append(handle)
    return unique


def _condition_entry(node: dict[str, Any]) -> dict[str, Any]:
    label = str(node.get("motion_structure_label") or node.get("display_name") or node.get("node_id"))
    aliases = list(node.get("caption_name_candidates") or node.get("caption_aliases") or [])
    return {
        "condition_id": _condition_id(label),
        "program_node_id": None,
        "motion_structure_label": label,
        "scope": _condition_scope(node),
        "review_status": _review_status(node),
        "condition_weight_default": 0.0,
        "promotion_policy": "requires_review_before_training_as_positive",
        "channels": list(node.get("channels") or []),
        "zones": list(node.get("zones") or []),
        "geometry_roles": list(node.get("family_core_items") or []),
        "support_cases_max": int(node.get("support_cases_max") or 0),
        "support_cases_sum": int(node.get("support_cases_sum") or 0),
        "structure_score_max": float(node.get("structure_score_max") or 0.0),
        "caption_name_candidates": aliases,
        "semantic_level": _semantic_level(node),
        "edit_scope": _edit_scope(node),
        "composition_policy": _composition_policy(node),
        "match_signature": _match_signature(node),
        "edit_handles": _edit_handles(node),
    }


def _program_node_id(source_node_id: str, node_kind: str) -> str:
    prefix = {
        "composition_root": "program_root",
        "structure_group": "program_structure_group",
        "composition_family": "program_family",
        "composition_variant": "program_variant",
    }.get(node_kind, "program_node")
    return f"{prefix}_{_safe_id(source_node_id)}"


def _convert_node(node: dict[str, Any], children: list[str]) -> dict[str, Any]:
    source_kind = str(node.get("node_kind") or "")
    program_id = _program_node_id(str(node.get("node_id") or ""), source_kind)
    converted = {
        "program_node_id": program_id,
        "source_node_id": str(node.get("node_id") or ""),
        "source_node_kind": source_kind,
        "program_node_kind": {
            "composition_root": "program_root",
            "structure_group": "structure_group",
            "composition_family": "composition_family",
            "composition_variant": "variant",
        }.get(source_kind, "unknown"),
        "display_name": node.get("display_name"),
        "motion_structure_label": node.get("motion_structure_label"),
        "review_status": _review_status(node),
        "scope": _condition_scope(node),
        "semantic_level": _semantic_level(node),
        "edit_scope": _edit_scope(node),
        "composition_policy": _composition_policy(node),
        "match_signature": _match_signature(node),
        "children": children,
    }
    for key in [
        "parent_root",
        "parent_structure_group_id",
        "parent_family_id",
        "family_count",
        "variant_count",
        "support_cases",
        "support_cases_max",
        "support_cases_sum",
        "occurrences",
        "occurrences_sum",
        "structure_score",
        "structure_score_max",
        "channels",
        "zones",
        "family_core_items",
        "geometry_clusters",
        "items",
        "caption_aliases",
        "caption_name_candidates",
        "caption_alias_purity",
        "caption_alias_purity_max",
        "top_source_symbols",
    ]:
        if key in node:
            converted[key] = node[key]
    if source_kind in {"structure_group", "composition_family"}:
        condition = _condition_entry(node)
        condition["program_node_id"] = program_id
        condition["condition_entry_id"] = "AMLCPNODE_" + _safe_id(program_id).upper()
        converted["condition_entry"] = condition
    return converted


def _build_search_index(program_nodes: list[dict[str, Any]]) -> dict[str, Any]:
    axes = {
        "channels": defaultdict(list),
        "zones": defaultdict(list),
        "cluster_ids": defaultdict(list),
        "event_families": defaultdict(list),
        "geometry_roles": defaultdict(list),
        "semantic_levels": defaultdict(list),
    }
    for node in program_nodes:
        node_id = str(node.get("program_node_id") or "")
        if not node_id:
            continue
        signature = node.get("match_signature") or {}
        for value in signature.get("required_channels") or []:
            axes["channels"][str(value)].append(node_id)
        for value in signature.get("required_zones") or []:
            axes["zones"][str(value)].append(node_id)
        for value in signature.get("required_cluster_ids") or []:
            axes["cluster_ids"][str(value)].append(node_id)
        for value in signature.get("required_event_families") or []:
            axes["event_families"][str(value)].append(node_id)
        for value in signature.get("geometry_roles") or []:
            axes["geometry_roles"][str(value)].append(node_id)
        level = str(node.get("semantic_level") or "")
        if level:
            axes["semantic_levels"][level].append(node_id)
    return {
        "index_version": "aml_composable_search_index_v0",
        "axes": {
            axis_name: {key: sorted(set(values)) for key, values in sorted(axis.items())}
            for axis_name, axis in axes.items()
        },
    }


def build_program(forest: dict[str, Any]) -> dict[str, Any]:
    source_nodes = {str(node.get("node_id") or ""): node for node in forest.get("nodes") or []}
    source_children = _child_index(list(forest.get("edges") or []))
    program_nodes: list[dict[str, Any]] = []
    source_to_program: dict[str, str] = {}

    for source_id, node in source_nodes.items():
        source_to_program[source_id] = _program_node_id(source_id, str(node.get("node_kind") or ""))

    for source_id, node in source_nodes.items():
        child_ids = [source_to_program[child] for child in source_children.get(source_id, []) if child in source_to_program]
        program_nodes.append(_convert_node(node, child_ids))

    program_node_by_id = {str(node["program_node_id"]): node for node in program_nodes}
    edges: list[dict[str, str]] = []
    for edge in forest.get("edges") or []:
        parent = source_to_program.get(str(edge.get("parent_node_id") or ""))
        child = source_to_program.get(str(edge.get("child_node_id") or ""))
        if parent and child:
            edges.append(
                {
                    "parent_program_node_id": parent,
                    "child_program_node_id": child,
                    "edge_type": str(edge.get("edge_type") or "program_edge"),
                }
            )

    condition_entries = [
        dict(node["condition_entry"])
        for node in program_nodes
        if isinstance(node.get("condition_entry"), dict)
    ]
    condition_entries.sort(
        key=lambda row: (
            str(row.get("scope") or ""),
            str(row.get("review_status") or ""),
            str(row.get("condition_id") or ""),
            str(row.get("program_node_id") or ""),
        )
    )

    node_kind_counts = Counter(str(node.get("program_node_kind") or "") for node in program_nodes)
    review_counts = Counter(str(node.get("review_status") or "") for node in program_nodes)
    scope_counts = Counter(str(row.get("scope") or "") for row in condition_entries)
    return {
        "schema_version": "aml_composable_pattern_program_v0",
        "runtime_policy": "candidate composable AML vocabulary; review before positive training labels",
        "source_forest_schema": forest.get("schema_version"),
        "source_forest_summary": forest.get("summary") or {},
        "summary": {
            "program_node_count": len(program_nodes),
            "edge_count": len(edges),
            "condition_entry_count": len(condition_entries),
            "node_kind_counts": dict(sorted(node_kind_counts.items())),
            "review_status_counts": dict(sorted(review_counts.items())),
            "condition_scope_counts": dict(sorted(scope_counts.items())),
        },
        "root_kind_map": ROOT_KIND_MAP,
        "nodes": sorted(program_nodes, key=lambda row: str(row.get("program_node_id") or "")),
        "edges": edges,
        "condition_vocabulary": condition_entries,
        "search_index": _build_search_index(program_nodes),
        "source_to_program_node_id": source_to_program,
        "program_node_index": {
            node_id: idx for idx, node_id in enumerate(sorted(program_node_by_id))
        },
    }


def write_tree(path: Path, program: dict[str, Any], *, max_children: int) -> None:
    nodes = {str(node.get("program_node_id") or ""): node for node in program.get("nodes") or []}
    children: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for edge in program.get("edges") or []:
        parent = str(edge.get("parent_program_node_id") or "")
        child = str(edge.get("child_program_node_id") or "")
        if child in nodes:
            children[parent].append(nodes[child])
    root_nodes = sorted(
        [node for node in nodes.values() if node.get("program_node_kind") == "program_root"],
        key=lambda row: str(row.get("program_node_id") or ""),
    )
    summary = program.get("summary") or {}
    lines = [
        "# AML Composable Pattern Program v0",
        "",
        f"nodes={summary.get('program_node_count')} edges={summary.get('edge_count')} "
        f"conditions={summary.get('condition_entry_count')}",
        "",
    ]
    for root in root_nodes:
        root_children = sorted(children.get(str(root["program_node_id"]), []), key=lambda row: str(row.get("program_node_id") or ""))
        lines.append(f"- {root.get('display_name')} [{len(root_children)} groups]")
        for group in root_children[:max_children]:
            condition = group.get("condition_entry") or {}
            aliases = ", ".join(f"{item['id']}:{item['count']}" for item in (condition.get("caption_name_candidates") or [])[:4])
            lines.append(
                f"  - {group.get('program_node_id')} | {group.get('review_status')} | "
                f"level={group.get('semantic_level')} edit={group.get('edit_scope')} "
                f"families={group.get('family_count')} variants={group.get('variant_count')} "
                f"condition={condition.get('condition_id')} aliases={aliases or 'none'}"
            )
            handles = ", ".join(item["name"] for item in condition.get("edit_handles") or [])
            lines.append(f"    handles: {handles}")
            for family in sorted(children.get(str(group["program_node_id"]), []), key=lambda row: str(row.get("program_node_id") or ""))[:5]:
                f_condition = family.get("condition_entry") or {}
                lines.append(
                    f"    - {family.get('program_node_id')} | {family.get('review_status')} | "
                    f"level={family.get('semantic_level')} edit={family.get('edit_scope')} "
                    f"variants={family.get('variant_count')} condition={f_condition.get('condition_id')}"
                )
        if len(root_children) > max_children:
            lines.append(f"    ... {len(root_children) - max_children} more groups")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_outputs(output_dir: Path, program: dict[str, Any], *, tree_children: int) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / "aml_composable_pattern_program.json", program)
    compact = {
        key: program[key]
        for key in ["schema_version", "runtime_policy", "source_forest_schema", "source_forest_summary", "summary", "root_kind_map"]
    }
    compact["nodes"] = [
        {
            key: node.get(key)
            for key in [
                "program_node_id",
                "source_node_id",
                "program_node_kind",
                "display_name",
                "motion_structure_label",
                "review_status",
                "scope",
                "semantic_level",
                "edit_scope",
                "composition_policy",
                "match_signature",
                "children",
                "family_count",
                "variant_count",
                "support_cases_max",
                "support_cases_sum",
                "structure_score_max",
                "channels",
                "zones",
                "family_core_items",
                "condition_entry",
            ]
            if key in node
        }
        for node in program.get("nodes") or []
        if node.get("program_node_kind") in {"program_root", "structure_group", "composition_family"}
    ]
    compact["edges"] = program.get("edges") or []
    compact["condition_vocabulary"] = program.get("condition_vocabulary") or []
    compact["search_index"] = program.get("search_index") or {}
    _write_json(output_dir / "aml_composable_pattern_program_compact.json", compact)
    _write_json(output_dir / "aml_condition_vocabulary.json", program.get("condition_vocabulary") or [])
    _write_json(output_dir / "aml_composable_pattern_search_index.json", program.get("search_index") or {})
    _write_json(output_dir / "summary.json", program.get("summary") or {})
    write_tree(output_dir / "aml_composable_pattern_program_tree.txt", program, max_children=tree_children)


def run_self_test() -> None:
    tiny_forest = {
        "schema_version": "tiny_forest",
        "summary": {},
        "nodes": [
            {"node_id": "composition_full_candidates", "node_kind": "composition_root", "display_name": "full"},
            {
                "node_id": "structure_group_0001_test",
                "node_kind": "structure_group",
                "status": "name_aligned_structure_group",
                "parent_root": "composition_full_candidates",
                "display_name": "bimanual_raise_spread_vertical_coordination",
                "motion_structure_label": "bimanual_raise_spread_vertical_coordination",
                "channels": ["bimanual", "whole_body_vertical"],
                "zones": ["upper", "vertical"],
                "family_core_items": ["bimanual:BIMANUAL_PERIODIC/BI_RAISE_SPREAD"],
                "support_cases_max": 10,
                "support_cases_sum": 12,
                "structure_score_max": 7.0,
                "caption_aliases": [{"id": "jumping_jack", "count": 9}],
                "caption_name_candidates": [{"id": "jumping_jack", "count": 9}],
                "family_count": 1,
                "variant_count": 2,
            },
        ],
        "edges": [
            {
                "parent_node_id": "composition_full_candidates",
                "child_node_id": "structure_group_0001_test",
                "edge_type": "structure_group_member",
            }
        ],
    }
    with tempfile.TemporaryDirectory() as tmp:
        program = build_program(tiny_forest)
        assert program["summary"]["condition_entry_count"] == 1
        condition = program["condition_vocabulary"][0]
        assert condition["condition_id"] == "AMLCP_BIMANUAL_RAISE_SPREAD_VERTICAL_COORDINATION"
        assert any(handle["name"] == "vertical_amplitude" for handle in condition["edit_handles"])
        write_outputs(Path(tmp), program, tree_children=5)
    print(json.dumps({"ok": True}, ensure_ascii=True, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser(description="Export composable AML pattern program from composition forest.")
    parser.add_argument("--forest-json", default=str(DEFAULT_FOREST_JSON))
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--tree-children", type=int, default=60)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        run_self_test()
        return

    forest = _read_json(Path(args.forest_json))
    program = build_program(forest)
    write_outputs(Path(args.output_dir), program, tree_children=int(args.tree_children))
    print(
        json.dumps(
            {
                "ok": True,
                "output_dir": str(args.output_dir),
                "summary": program["summary"],
            },
            ensure_ascii=True,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
